# PlatformIO Project Configuration Override
# ESP32-C3 Supermini with WS2812 on GPIO1 and DMX on UART1
# ------------------------------------------------------------------------------

[platformio]
default_envs = esp32c3_supermini_dmx

[env:esp32c3_supermini_dmx]
extends = env:esp32c3dev
build_flags = 
  ${env:esp32c3dev.build_flags}
  -D WLED_ENABLE_DMX
  -D WLED_RELEASE_NAME=\"ESP32-C3-DMX\"
  -D CLIENT_SSID='"SSID"'
  -D CLIENT_PASS='"PW"'
  -D WLED_DEBUG

; ESP32 DMX output uses SparkFunDMX and hardcodes txPin = 2 in SparkFunDMX.cpp:24-40.
; After adjustments
; -D DMX_TX_PIN=2

; ESP32-C3 with DMX enabled defaults to GPIO1.
; ESP32 (no Ethernet) defaults to GPIO16.
; ESP8266 defaults to GPIO2 (unless DMX enabled, then GPIO1).

; ATTENTION:
; comments may effect the build, even though they look disabled inline

[env:esp32dev_dean]
extends = env:esp32dev
build_flags = 
  ${env:esp32dev.build_flags}
  -D WLED_ENABLE_DMX
  -D WLED_RELEASE_NAME=\"ESP32-DMX\"
  -D CLIENT_SSID='"SSID"'
  -D CLIENT_PASS='"PW"'
  -D DMX_TX_PIN=21
  -D DATA_PINS=16
  -D I2S_SDPIN=32
  -D I2S_WSPIN=15
  -D I2S_CKPIN=14
  ; -D I2S_SDPIN=32; GPIO for SD pin on digital microphone (32)
  ; -D I2S_WSPIN=15; GPIO for WS pin on digital microphone (15)
  ; -D I2S_CKPIN=14; GPIO for SCK pin on digital microphone (14)
  ; -D WLED_DEBUG
; upload_speed = 115200