# PlatformIO Project Configuration Override
# ESP32-C3 Supermini with WS2812 on GPIO1 and DMX on UART1
# ------------------------------------------------------------------------------

[platformio]
default_envs = esp32c3_supermini_dmx

[env:esp32c3_supermini_dmx]
extends = env:esp32c3dev
build_flags = 
  ${env:esp32c3dev.build_flags}
  -D WLED_ENABLE_DMX
  -D WLED_RELEASE_NAME=\"ESP32-C3-DMX\"
  -D CLIENT_SSID='"SSID"'
  -D CLIENT_PASS='"PW"'
  -D WLED_DEBUG

; ESP32 DMX output uses SparkFunDMX and hardcodes txPin = 2 in SparkFunDMX.cpp:24-40.
; After adjustments
; -D DMX_TX_PIN=2

; ESP32-C3 with DMX enabled defaults to GPIO1.
; ESP32 (no Ethernet) defaults to GPIO16.
; ESP8266 defaults to GPIO2 (unless DMX enabled, then GPIO1).

[env:esp32dev_dean]
extends = env:esp32dev
build_flags = 
  ${env:esp32dev.build_flags}
  -D WLED_ENABLE_DMX
  -D WLED_RELEASE_NAME=\"ESP32-DMX\"
  -D CLIENT_SSID='"SSID"'
  -D CLIENT_PASS='"PW"'
  ; -D WLED_DEBUG
  -D DMX_TX_PIN=2
  ; -D DMX_TX_PIN=17
  -D DATA_PINS=16
  ; -D DATA_PINS=1